

name: Verify installation


on:
  [ push, pull_request ]

jobs:

  VerifyInstallation:

    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2
        with:
          ref : ${{ github.event.pull_request.head.sha }}
          path: gnu-koryavov

      - name: Build docker image
        run: |
            echo "Creating docker image..." &&
            ls -la &&
            cp gnu-koryavov/ci-scripts/Dockerfile . &&
            docker build -t installation:v1.0 .

      - name: Run image and test installation
        run: |
          image_name=$(docker ps -a | grep "installation:")
         # echo "Running image: $image_name" &&
         # docker run -d installation:v1.0




    

